version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-vite-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
